#
# Jekyll configuration
#
auto: true
permalink: /:year/:month/:title.html
pygments: true
#lsi: true
paginate: 6
markdown: rdiscount
rdiscount
  extensions: [smart]

#
# Site configuration
#
base_url: "http://www.beta4better.me"	# L'URL de votre site
url: "http://www.beta4better.me"	# L'URL de votre site
title: "Charles Collection"	# Titre de votre site
description: "PURSUE SOMETHING SO IMPORTANT THAT EVEN IF YOU FAIL, THE WORLD IS BETTER OFF WITH YOU HAVING TRIED."	# La meta description sur la page d'accueil de votre site
author: "Charles Yuan"	# Votre nom
email: "charles@beta4better.me"	# Votre email
rss_feed: "/atom.xml"	# If you are using Feedburner, enter your feedburner address here.
gauaid: "UA-9439246-12"	# Votre numéro de tracking Google Analytics


#
# Comments
#
disqusshortname: "beta4better"	# Votre Shortname Disqus
fb_appid: ""	# Votre ID d'application Facebook
fb_comments: ""	# true pour activer les commentaires Facebook


#
# Socialize
#
socialize: "true"
socialize_twitter: "beta4better" # Votre username Twitter
socialize_googleplus: "109115007895857662538" # Votre ID Google+
socialize_github: "beta4better" # Votre username GitHub
